const C={blue:'#1677ff',cyan:'#19b6c9',green:'#2eb67d',orange:'#f59e0b',navy:'#254b6d',gray:'#c7d2de'};const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];let D=[],charts={};
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const hm=v=>v/1e6,dam=v=>v/1e3;const fmtHm=v=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:1,minimumFractionDigits:1}).format(v)+' hm³',fmtDam=v=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:1}).format(v)+' dam³',fmtDaily=v=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:0}).format(v)+' m³/día';
const sum=(pred,y,m=12)=>D.filter(r=>+r.d.slice(0,4)===y && +r.d.slice(5,7)<=m && pred(r)).reduce((a,r)=>a+r.v,0);
const capPred=name=>r=>r.tipo==='AGUA CAPTADA'&&r.sub==='AGUA BRUTA'&&(name==='Melonares'?norm(r.p2)==='MELONARES':name==='Gergal'?norm(r.p1)==='GERGAL':norm(r.p1)==='MINILLA');
const interPred=sub=>r=>norm(r.sub)===norm(sub);
function distributed(y,m,sevillaOnly=false){const produced=sum(r=>norm(r.sub)==='AGUA PRODUCIDA ETAP',y,m)+sum(interPred('AGUA TRATADA IMPORTADA'),y,m);const exports=sum(interPred('AGUA TRATADA EXPORTADA'),y,m);const total=produced-exports;if(!sevillaOnly)return total;return Math.max(0,produced-sum(r=>norm(r.sub)==='AGUA TRATADA IMPORTADA'||norm(r.sub)==='AGUA TRATADA EXPORTADA'||(norm(r.sub)==='AGUA PRODUCIDA ETAP'&&norm(r.p1)!=='ETAP CARAMBOLO'),y,m));}
function chart(id,type,data,options={},formatter=fmtHm){if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),{type,data,options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{boxWidth:9,usePointStyle:true,font:{size:10}}},tooltip:{callbacks:{label:c=>' '+c.dataset.label+': '+formatter(c.raw)}}},scales:{x:{grid:{display:false},ticks:{font:{size:9},color:'#738394'}},y:{beginAtZero:true,grid:{color:'#edf1f5'},ticks:{font:{size:9},color:'#738394',callback:v=>v.toLocaleString('es-ES')}},...(options.scales||{})},...options}})}
function monthly(sub,y){return months.map((_,i)=>dam(sum(interPred(sub),y,i+1)-sum(interPred(sub),y,i)));}function periodMonth(yy,y,m){return yy<y?12:m}function elapsedDays(yy,y,m){const lm=periodMonth(yy,y,m);return Math.round((Date.UTC(yy,lm,1)-Date.UTC(yy,0,1))/86400000)}function capturedDaily(name,yy,y,m){const days=elapsedDays(yy,y,m);return days?sum(capPred(name),yy,periodMonth(yy,y,m))/days:0}
function update(){const y=+year.value,m=+month.value,prev=y-1;const ys=Array.from({length:11},(_,i)=>y-10+i);periodText.textContent=`Datos hasta ${months[m-1].toLowerCase()} de ${y} · comparación histórica`;capSub.textContent=`Promedio diario · años anteriores completos y ${y} hasta ${months[m-1].toLowerCase()}`;distSub.textContent=`Acumulado enero–${months[m-1].toLowerCase()} por año`;popSub.textContent=`${y} frente a ${prev} · enero–${months[m-1].toLowerCase()}`;const captured=['Melonares','Gergal','Minilla'].reduce((a,n)=>a+capturedDaily(n,y,y,m),0),dist=distributed(y,m),dp=distributed(prev,m);k1.textContent=fmtDaily(captured);k2.textContent=fmtHm(hm(dist));const bal=sum(interPred('AGUA TRATADA IMPORTADA'),y,m)-sum(interPred('AGUA TRATADA EXPORTADA'),y,m);k3.textContent=fmtHm(hm(bal));const pct=dp?(dist/dp-1)*100:0;k4.textContent=(pct>=0?'+':'')+pct.toLocaleString('es-ES',{maximumFractionDigits:1})+' %';k4.style.color=pct>=0?C.green:'#d64545';chart('captada','bar',{labels:ys,datasets:[{label:'Melonares',data:ys.map(z=>capturedDaily('Melonares',z,y,m)),backgroundColor:C.blue,borderRadius:3},{label:'Gergal',data:ys.map(z=>capturedDaily('Gergal',z,y,m)),backgroundColor:C.cyan,borderRadius:3},{label:'Minilla',data:ys.map(z=>capturedDaily('Minilla',z,y,m)),backgroundColor:C.navy,borderRadius:3}]},{scales:{x:{stacked:true},y:{stacked:true,title:{display:true,text:'m³/día'}}}},fmtDaily);[['bruta','AGUA ADUCIDA BRUTA EXPORTADA',C.orange],['importada','AGUA TRATADA IMPORTADA',C.green],['exportada','AGUA TRATADA EXPORTADA',C.blue]].forEach(([id,sub,col])=>chart(id,'bar',{labels:months,datasets:[{label:String(prev),data:monthly(sub,prev),backgroundColor:C.gray,borderRadius:3},{label:String(y),data:monthly(sub,y).map((v,i)=>i<m?v:null),backgroundColor:col,borderRadius:3}]},{scales:{y:{title:{display:true,text:'dam³'}}}},fmtDam));chart('distribuida','line',{labels:ys,datasets:[{label:'Sevilla',data:ys.map(z=>hm(distributed(z,m,true))),borderColor:C.blue,backgroundColor:C.blue,tension:.3,pointRadius:3},{label:'Resto de poblaciones',data:ys.map(z=>hm(distributed(z,m)-distributed(z,m,true))),borderColor:C.green,backgroundColor:C.green,tension:.3,pointRadius:3}]},{},fmtHm);const popNames=['Aljarafesa','Huesna','Burguillos','El Garrobo','El Ronquillo','Adufe','Mairena del Alcor','La Galbana'];const popVal=(n,yy)=>{if(['Aljarafesa','Huesna','Burguillos'].includes(n))return hm(sum(r=>norm(r.sub)==='AGUA TRATADA EXPORTADA'&&norm(r.p1).includes(norm(n)),yy,m));return hm(sum(r=>(norm(r.sub)==='AGUA PRODUCIDA ETAP'||norm(r.sub)==='AGUA TRATADA IMPORTADA')&&(norm(r.p1).includes(norm(n))||norm(r.p2).includes(norm(n))),yy,m));};chart('poblaciones','bar',{labels:popNames,datasets:[{label:String(prev),data:popNames.map(n=>popVal(n,prev)),backgroundColor:C.gray,borderRadius:3},{label:String(y),data:popNames.map(n=>popVal(n,y)),backgroundColor:C.blue,borderRadius:3}]},{indexAxis:'y'},fmtHm);}
fetch('datos-red.json').then(r=>r.json()).then(x=>{D=x;const years=[...new Set(D.map(r=>+r.d.slice(0,4)))].sort((a,b)=>a-b);month.innerHTML=months.map((n,i)=>`<option value="${i+1}" ${i===7?'selected':''}>${n}</option>`).join('');year.innerHTML=years.map(n=>`<option ${n===2023?'selected':''}>${n}</option>`).join('');refresh.onclick=update;month.onchange=update;year.onchange=update;update();loading.style.display='none'}).catch(e=>{loading.textContent='No se pudieron cargar los datos. Abre la carpeta mediante un servidor web local.';console.error(e)});
