const COLS=['FECHA','COD_DISP','NOM_DISP','POBLA','COD_SEÑAL','CMD','CMES','OBS'];const LABELS={FECHA:'Fecha',COD_DISP:'Código disp.',NOM_DISP:'Nombre dispositivo',POBLA:'Población',COD_SEÑAL:'Código señal',CMD:'CMD',CMES:'CMES',OBS:'Observación'};let rows=[],filtered=[],page=1,editingId=null,changes=0;const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const fmtDate=v=>v?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:'';const fmtNum=v=>v==null?'':Number(v).toLocaleString('es-ES',{maximumFractionDigits:2});
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}function dirty(){changes++;$('dirtyBadge').hidden=false;$('dirtyBadge').textContent=`${changes} cambio${changes===1?'':'s'}`}
function initHead(){$('headRow').innerHTML=COLS.map(c=>`<th>${LABELS[c]}</th>`).join('')+'<th>Acciones</th>';$('filterRow').innerHTML=COLS.map(c=>`<th><input data-col="${c}" aria-label="Filtrar ${LABELS[c]}" placeholder="Filtrar..."></th>`).join('')+'<th></th>';$('filterRow').querySelectorAll('input').forEach(i=>i.oninput=()=>{page=1;applyFilters()})}
function initDates(){const years=[...new Set(rows.map(r=>r.FECHA?.slice(0,4)).filter(Boolean))].sort();$('yearFilter').innerHTML='<option value="">Todos</option>'+years.map(y=>`<option>${y}</option>`).join('');$('monthFilter').innerHTML='<option value="">Todos</option>'+['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((m,i)=>`<option value="${String(i+1).padStart(2,'0')}">${m}</option>`).join('')}
function applyFilters(){const y=$('yearFilter').value,m=$('monthFilter').value,g=$('globalFilter').value.trim().toLowerCase(),cf={};$('filterRow').querySelectorAll('input').forEach(i=>cf[i.dataset.col]=i.value.trim().toLowerCase());filtered=rows.filter(r=>{if(y&&r.FECHA?.slice(0,4)!==y)return false;if(m&&r.FECHA?.slice(5,7)!==m)return false;if(g&&!COLS.some(c=>String(r[c]??'').toLowerCase().includes(g)))return false;return COLS.every(c=>!cf[c]||String(r[c]??'').toLowerCase().includes(cf[c]))});const pages=Math.max(1,Math.ceil(filtered.length/+$('pageSize').value));page=Math.min(page,pages);render()}
function render(){const size=+$('pageSize').value,start=(page-1)*size,list=filtered.slice(start,start+size);$('tableBody').innerHTML=list.map(r=>`<tr>${COLS.map(c=>{if(c==='OBS')return `<td class="obs">${r.OBS?`<span class="obsDot" title="${esc(r.OBS)}">i</span>`:''}</td>`;if(c==='FECHA')return `<td>${fmtDate(r[c])}</td>`;if(c==='CMD'||c==='CMES')return `<td class="num">${fmtNum(r[c])}</td>`;return `<td>${esc(r[c])}</td>`}).join('')}<td class="actions"><button onclick="openEdit(${r._id})" title="Editar">✎</button><button class="delete" onclick="removeRow(${r._id})" title="Eliminar">⌫</button></td></tr>`).join('')||'<tr><td colspan="9">No hay registros que coincidan con los filtros.</td></tr>';const pages=Math.max(1,Math.ceil(filtered.length/size));$('rowCount').textContent=`${filtered.length.toLocaleString('es-ES')} registros`;$('pageInfo').textContent=`Página ${page} de ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages}
function openEdit(id){editingId=id;const r=id==null?{FECHA:new Date().toISOString().slice(0,10),COD_DISP:'',NOM_DISP:'',POBLA:'',COD_SEÑAL:'',CMD:0,CMES:0,OBS:''}:rows.find(x=>x._id===id);$('modalTitle').textContent=id==null?'Añadir registro':'Editar registro';$('editFields').innerHTML=COLS.map(c=>`<label class="${c==='OBS'?'full':''}">${LABELS[c]}${c==='OBS'?`<textarea name="${c}">${esc(r[c])}</textarea>`:`<input name="${c}" type="${c==='FECHA'?'date':c==='CMD'||c==='CMES'?'number':'text'}" step="any" value="${esc(r[c])}">`}</label>`).join('');$('editDialog').showModal()}
function saveEdit(e){e.preventDefault();const fd=new FormData($('editDialog').querySelector('form')),obj={};COLS.forEach(c=>obj[c]=c==='CMD'||c==='CMES'?Number(fd.get(c)||0):fd.get(c));if(!obj.FECHA){toast('La fecha es obligatoria');return}if(editingId==null){obj._id=Math.max(0,...rows.map(r=>r._id))+1;rows.unshift(obj)}else Object.assign(rows.find(r=>r._id===editingId),obj);$('editDialog').close();dirty();applyFilters();toast('Registro guardado')}
function removeRow(id){const r=rows.find(x=>x._id===id);if(!confirm(`¿Eliminar el registro ${r.COD_DISP||''} de ${fmtDate(r.FECHA)}?`))return;rows=rows.filter(x=>x._id!==id);dirty();applyFilters();toast('Registro eliminado')}
function saveExcel(){const data=rows.map(r=>{const o={};COLS.forEach(c=>o[c]=c==='FECHA'&&r[c]?new Date(`${r[c]}T00:00:00`):r[c]);return o});const ws=XLSX.utils.json_to_sheet(data,{header:COLS});ws['!cols']=[{wch:12},{wch:16},{wch:38},{wch:30},{wch:20},{wch:15},{wch:15},{wch:55}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Balance_Pobla');XLSX.writeFile(wb,'BD_Balance_Poblaciones_modificado.xlsx',{compression:true});toast('Excel descargado. Súbelo a GitHub para conservar los cambios.')}
window.openEdit=openEdit;window.removeRow=removeRow;$('confirmEdit').onclick=saveEdit;$('addRow').onclick=()=>openEdit(null);$('saveExcel').onclick=saveExcel;$('yearFilter').onchange=()=>{page=1;applyFilters()};$('monthFilter').onchange=()=>{page=1;applyFilters()};$('globalFilter').oninput=()=>{page=1;applyFilters()};$('pageSize').onchange=()=>{page=1;applyFilters()};$('prevPage').onclick=()=>{page--;render()};$('nextPage').onclick=()=>{page++;render()};$('clearFilters').onclick=()=>{$('yearFilter').value='';$('monthFilter').value='';$('globalFilter').value='';$('filterRow').querySelectorAll('input').forEach(i=>i.value='');page=1;applyFilters()};
fetch('balance-poblaciones/datos.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{rows=data;initHead();initDates();applyFilters()}).catch(e=>{$('rowCount').textContent='Error al cargar datos';toast('No se pudo cargar balance-poblaciones/datos.json');console.error(e)});
