const DATASETS={
 balance:{label:'Balance de poblaciones',file:'balance-poblaciones/BD_Balance_Poblaciones.xlsx',sheet:'Balance_Pobla',download:'BD_Balance_Poblaciones_modificado.xlsx',cols:['FECHA','COD_DISP','NOM_DISP','POBLA','COD_SEÑAL','CMD','CMES','OBS'],labels:{FECHA:'Fecha',COD_DISP:'Código disp.',NOM_DISP:'Nombre dispositivo',POBLA:'Población',COD_SEÑAL:'Código señal',CMD:'CMD',CMES:'CMES',OBS:'Estado'},numeric:['CMD','CMES'],notes:'OBS'},
 red:{label:'Datos de la Red',file:'balance-poblaciones/BD_Datos_Red.xlsx',sheet:'Datos_Red',download:'BD_Datos_Red_modificado.xlsx',cols:['FECHA','ID','TIPO','SUBTIPO','PROCEDENCIA_1','PROCEDENCIA_2','MEDICION','AJUSTE','OBSERVACIONES'],labels:{FECHA:'Fecha',ID:'ID',TIPO:'Tipo',SUBTIPO:'Subtipo',PROCEDENCIA_1:'Procedencia 1',PROCEDENCIA_2:'Procedencia 2',MEDICION:'Medición',AJUSTE:'Ajuste',OBSERVACIONES:'Observaciones'},numeric:['ID','MEDICION','AJUSTE'],notes:'OBSERVACIONES'}
};
let activeKey='balance',rows=[],filtered=[],page=1,editingId=null,sortColumn='FECHA',sortDirection='asc';
const stores={balance:{rows:null,changes:0},red:{rows:null,changes:0},longitud:{rows:null,changes:0}},$=id=>document.getElementById(id),cfg=()=>DATASETS[activeKey];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pad=n=>String(n).padStart(2,'0');
function excelDate(v){if(v==null||v==='')return'';if(v instanceof Date&&!isNaN(v))return`${v.getFullYear()}-${pad(v.getMonth()+1)}-${pad(v.getDate())}`;if(typeof v==='number'){const o=XLSX.SSF.parse_date_code(v);return o?`${o.y}-${pad(o.m)}-${pad(o.d)}`:''}const s=String(v).trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${pad(m[2])}-${pad(m[1])}`:''}
const displayDate=v=>{const s=excelDate(v);return s?`${s.slice(8,10)}/${s.slice(5,7)}/${s.slice(0,4)}`:''};
const num=v=>v==null||v===''?'':Number(v).toLocaleString('es-ES',{maximumFractionDigits:2});
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2300)}
function dirty(){const st=stores[activeKey];st.changes++;const b=$(activeKey==='balance'?'dirtyBadgeBalance':'dirtyBadgeRed');b.hidden=false;b.textContent=`${st.changes} cambio${st.changes===1?'':'s'}`}
function build(){
 const c=cfg();
 $('headRow').innerHTML=c.cols.map(x=>`<th><button class="sortButton" data-sort="${x}">${c.labels[x]} <span class="sortIcon">↕</span></button></th>`).join('')+'<th>Acciones</th>';
 $('headRow').querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>changeSort(b.dataset.sort));
 const selectCols=activeKey==='longitud'?['FECHA','COD','POBLACIÓN']:[];
 $('filterRow').innerHTML=c.cols.map(x=>{
  if(selectCols.includes(x)){
   const values=[...new Set(rows.map(r=>x==='FECHA'?displayDate(r[x]):String(r[x]??'').trim()).filter(Boolean))];
   values.sort((a,b)=>x==='FECHA'?excelDate(a).localeCompare(excelDate(b)):a.localeCompare(b,'es',{sensitivity:'base'}));
   const label=x==='FECHA'?'Todas las fechas':x==='COD'?'Todos':'Todas las poblaciones';
   return `<th><select data-col="${x}"><option value="">${label}</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></th>`;
  }
  return `<th><input data-col="${x}" placeholder="Filtrar..."></th>`;
 }).join('')+'<th></th>';
 $('filterRow').querySelectorAll('input,select').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{page=1;applyFilters()}));
 const ys=[...new Set(rows.map(r=>r.FECHA.slice(0,4)).filter(Boolean))].sort();
 $('yearFilter').innerHTML='<option value="">Todos</option>'+ys.map(y=>`<option>${y}</option>`).join('');
 $('monthFilter').innerHTML='<option value="">Todos</option>'+['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((m,i)=>`<option value="${pad(i+1)}">${m}</option>`).join('')
}
function compare(a,b,col){let av=a[col]??'',bv=b[col]??'';if(col==='FECHA'){av=excelDate(av);bv=excelDate(bv)}else if(cfg().numeric.includes(col)){av=Number(av)||0;bv=Number(bv)||0}else{av=String(av).toLocaleLowerCase('es');bv=String(bv).toLocaleLowerCase('es')}return av<bv?-1:av>bv?1:0}
function changeSort(col){sortDirection=sortColumn===col&&sortDirection==='asc'?'desc':'asc';sortColumn=col;page=1;applyFilters()}
function applyFilters(){const c=cfg(),y=$('yearFilter').value,m=$('monthFilter').value,g=$('globalFilter').value.trim().toLowerCase(),cf={};$('filterRow').querySelectorAll('input,select').forEach(i=>cf[i.dataset.col]=i.value.trim().toLowerCase());filtered=rows.filter(r=>(!y||r.FECHA.slice(0,4)===y)&&(!m||r.FECHA.slice(5,7)===m)&&(!g||c.cols.some(x=>String(r[x]??'').toLowerCase().includes(g)))&&c.cols.every(x=>!cf[x]||String(x==='FECHA'?displayDate(r[x]):r[x]??'').toLowerCase().includes(cf[x])));filtered.sort((a,b)=>compare(a,b,sortColumn)*(sortDirection==='asc'?1:-1));$('headRow').querySelectorAll('[data-sort]').forEach(b=>{b.querySelector('.sortIcon').textContent=b.dataset.sort===sortColumn?(sortDirection==='asc'?'▲':'▼'):'↕';b.classList.toggle('active',b.dataset.sort===sortColumn)});page=Math.min(page,Math.max(1,Math.ceil(filtered.length/+$('pageSize').value)));render()}
function noteCell(v){const t=String(v??'').trim();return t?`<span class="observationWrapper"><span class="statusBadge incident">Observación</span><span class="observationTooltip">${esc(t)}</span></span>`:'<span class="statusBadge normal">Normal</span>'}
function render(){const c=cfg(),size=+$('pageSize').value,start=(page-1)*size,list=filtered.slice(start,start+size);$('tableBody').innerHTML=list.map(r=>`<tr>${c.cols.map(x=>x===c.notes?`<td class="statusCell">${noteCell(r[x])}</td>`:x==='FECHA'?`<td>${displayDate(r[x])}</td>`:c.numeric.includes(x)?`<td>${num(r[x])}</td>`:`<td>${esc(r[x])}</td>`).join('')}<td class="actions"><button class="iconAction edit" onclick="openEdit(${r._id})" title="Editar"><svg viewBox="0 0 24 24"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg></button><button class="iconAction delete" onclick="removeRow(${r._id})" title="Eliminar"><svg viewBox="0 0 24 24"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v5M14 11v5"/></svg></button></td></tr>`).join('')||`<tr><td colspan="${c.cols.length+1}">Sin resultados</td></tr>`;const pages=Math.max(1,Math.ceil(filtered.length/size));$('rowCount').textContent=`${filtered.length.toLocaleString('es-ES')} registros`;$('pageInfo').textContent=`Página ${page} de ${pages}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages}
function openEdit(id){const c=cfg();editingId=id;const r=id==null?Object.fromEntries(c.cols.map(x=>[x,x==='FECHA'?excelDate(new Date()):c.numeric.includes(x)?0:''])):rows.find(x=>x._id===id);$('modalTitle').textContent=id==null?'Añadir registro':'Editar registro';$('editFields').innerHTML=c.cols.map(x=>`<label class="${x===c.notes?'full':''}">${c.labels[x]}${x===c.notes?`<textarea name="${x}">${esc(r[x])}</textarea>`:`<input name="${x}" type="${x==='FECHA'?'date':c.numeric.includes(x)?'number':'text'}" step="any" value="${esc(r[x])}">`}</label>`).join('');$('editDialog').showModal()}
function saveEdit(e){e.preventDefault();const c=cfg(),fd=new FormData($('editDialog').querySelector('form')),o={};c.cols.forEach(x=>o[x]=c.numeric.includes(x)?Number(fd.get(x)||0):String(fd.get(x)??'').trim());o.FECHA=excelDate(o.FECHA);if(!o.FECHA)return toast('La fecha es obligatoria');if(editingId==null){o._id=Math.max(0,...rows.map(r=>r._id))+1;rows.unshift(o)}else Object.assign(rows.find(r=>r._id===editingId),o);stores[activeKey].rows=rows;$('editDialog').close();dirty();applyFilters();toast('Registro guardado')}
function removeRow(id){if(!confirm('¿Eliminar este registro?'))return;rows=rows.filter(x=>x._id!==id);stores[activeKey].rows=rows;dirty();applyFilters();toast('Registro eliminado')}
function saveExcel(){const c=cfg(),data=rows.map(r=>Object.fromEntries(c.cols.map(x=>[x,x==='FECHA'?(()=>{const[y,m,d]=r.FECHA.split('-').map(Number);return new Date(y,m-1,d)})():r[x]])));const ws=XLSX.utils.json_to_sheet(data,{header:c.cols,cellDates:true,dateNF:'dd/mm/yyyy'});ws['!cols']=c.cols.map(x=>({wch:x===c.notes?65:x.includes('PROCEDENCIA')||x==='TIPO'||x==='SUBTIPO'?32:16}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,c.sheet);XLSX.writeFile(wb,c.download,{compression:true,cellDates:true});toast('Excel descargado')}
async function switchDataset(key){activeKey=key;document.querySelectorAll('.tab[data-dataset]').forEach(b=>b.classList.toggle('active',b.dataset.dataset===key));page=1;sortColumn='FECHA';sortDirection='asc';$('globalFilter').value='';$('rowCount').textContent='Cargando…';if(stores[key].rows){rows=stores[key].rows;build();applyFilters();return}try{const c=cfg(),res=await fetch(c.file,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);const wb=XLSX.read(await res.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[c.sheet]||wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:true}).map((r,i)=>{const o={_id:i+1};c.cols.forEach(x=>o[x]=x==='FECHA'?excelDate(r[x]):c.numeric.includes(x)?Number(r[x]||0):r[x]??'');return o});stores[key].rows=rows;build();applyFilters()}catch(e){console.error(e);$('rowCount').textContent='No se pudo abrir el Excel';toast(`Error cargando ${cfg().file.split('/').pop()}`)}}
window.openEdit=openEdit;window.removeRow=removeRow;$('confirmEdit').onclick=saveEdit;$('addRow').onclick=()=>openEdit(null);$('saveExcel').onclick=saveExcel;document.querySelectorAll('.tab[data-dataset]').forEach(b=>b.onclick=()=>switchDataset(b.dataset.dataset));['yearFilter','monthFilter'].forEach(id=>$(id).onchange=()=>{page=1;applyFilters()});$('globalFilter').oninput=()=>{page=1;applyFilters()};$('pageSize').onchange=()=>{page=1;applyFilters()};$('prevPage').onclick=()=>{page--;render()};$('nextPage').onclick=()=>{page++;render()};$('clearFilters').onclick=()=>{$('yearFilter').value='';$('monthFilter').value='';$('globalFilter').value='';$('filterRow').querySelectorAll('input,select').forEach(i=>i.value='');page=1;applyFilters()};switchDataset('balance');
